name: deploy-website-to-s3
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main]
    paths:
      - "supply/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./supply

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: website-artifact
          path: /dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUCKET: s3://portalfacturas.app/
      DISTRIBUTION_ID: E1CQH53WN8K5LF
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: website-artifact
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 sync ./ $BUCKET
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
