name: deploy-website-to-s3
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [main]
    paths:
      - "supply/**"
jobs:
  build-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: cd supply/
      - run: npm install
      - run: npm build
